[build]
    command = "hugo"
    publish = "public"
    functions = "functions"

[build.environment]
    HUGO_VERSION = "0.80.0"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "hugo -b $DEPLOY_PRIME_URL"

[[headers]]
    for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

# Friendly URLs for gazette RSS feeds
[[redirects]]
    from = "/feeds/gazette"
    to = "/.netlify/functions/gazette-rss"
    status = 200

[[redirects]]
    from = "/feeds/gazette.xml"
    to = "/.netlify/functions/gazette-rss"
    status = 200

[[redirects]]
    from = "/feeds/iulaan"
    to = "/.netlify/functions/iulaan-rss"
    status = 200

[[redirects]]
    from = "/feeds/iulaan.xml"
    to = "/.netlify/functions/iulaan-rss"
    status = 200
